#cloud-config
server_url: https://<new_cluster_server_ip>
token: token           # replace with the token you set when creating a new cluster
os:
  password: root  # replace with a your password
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
install:
  mode: join
  device: /dev/sda
  iso_url: http://147.28.156.11:52080/harvester-v1.0.2-amd64.iso
  tty: ttyS1,115200n8
