#cloud-config
token: token           # replace with a desired token
os:
  password: root   # replace with a your password
  ntp_servers:
  - 0.suse.pool.ntp.org
  - 1.suse.pool.ntp.org
install:
  mode: create
  device: /dev/sda
  iso_url: http://yufa-dev.s3.ap-east-1.amazonaws.com/harvester-v1.0.3-rc1-amd64.iso
  tty: ttyS1,115200n8
  vip: ${management_private_id}
  vip_mode: static
